version: '3.9'
services:
  ssh.cyrhades.fr:
    build: ./docker/ssh
  webssh.cyrhades.fr:
    build: ./docker/webssh
    ports:
      - ${PORT}:8888
  voila.cyrhades.fr:
    image: anssi/fcsc2025-misc-voila:latest
    ports:
      - ${PORT_SSH}:4000
